In [ ]:
# Program: write a program to find add, sub, mult, div of these two matrices.

# x = [[2, 7, 3],
#      [4, 5, 6],
#      [7, 8, 9]]
 
# y = [[5, 8, 1],
#     [6, 7, 3],
#     [4, 5, 9]]

In [1]:
import numpy as np

In [2]:
x = [[2, 7, 3],
     [4, 5, 6],
     [7, 8, 9]]

y = [[5, 8, 1],
     [6, 7, 3],
     [4, 5, 9]]

In [3]:
x_array = np.array(x)

In [4]:
x_array = np.array(x).flatten()
y_array = np.array(y).flatten()
add = x_array + y_array
sub = x_array - y_array
mult = x_array * y_array
div = x_array / y_array

In [6]:
print("Addition of two matrices is: ", np.array(add).reshape(3,3))
print("Substraction of two matrices is: ", np.array(sub).reshape(3,3))
print("Multiplication of two matrices is: ", np.array(mult).reshape(3,3))
print("Division of two matrices is: ", np.array(div).reshape(3,3))

Addition of two matrices is:  [[ 7 15  4]
 [10 12  9]
 [11 13 18]]
Substraction of two matrices is:  [[-3 -1  2]
 [-2 -2  3]
 [ 3  3  0]]
Multiplication of two matrices is:  [[10 56  3]
 [24 35 18]
 [28 40 81]]
Division of two matrices is:  [[0.4        0.875      3.        ]
 [0.66666667 0.71428571 2.        ]
 [1.75       1.6        1.        ]]
